version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_HOST_NAME=10.0.75.2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
