version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  #    volumes:
  #      - zookeeper_data:/opt/zookeeper-3.4.13/data
  kafka_0:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=deng2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_MIN_INSYNC_REPLICAS=1
      # - KAFKA_DELETE_TOPIC_ENABLE=TRUE
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      #create topic test with partitions 4 and replication factor 2
      #- KAFKA_CREATE_TOPICS="test:4:2"
    volumes:
      # - kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka_1:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - 19092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=deng2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_MIN_INSYNC_REPLICAS=1
      # - KAFKA_DELETE_TOPIC_ENABLE=TRUE
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      #create topic test with partitions 4 and replication factor 2
      #- KAFKA_CREATE_TOPICS="test:4:2"
    volumes:
      # - kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka_2:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - 29092:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=deng2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_MIN_INSYNC_REPLICAS=1
      # - KAFKA_DELETE_TOPIC_ENABLE=TRUE
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      #create topic test with partitions 4 and replication factor 2
      #- KAFKA_CREATE_TOPICS="test:4:2"
    volumes:
      # - kafka_data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local
